version: '3'
services:
  bq-demo-01:
    #配置容器名
    container_name: biuqu-demo-01
    # 指定镜像名
    image: biuqu/bq-demo:1.1
    ports:
      # 暴露端口
      - "9993:9993"
    volumes:
      # 创建容器数据卷
      - ~/docker/bq-clusters/logs/01:/opt/apps/bq-clusters/logs/
  bq-demo-02:
    #配置容器名
    container_name: biuqu-demo-02
    # 指定镜像名
    image: biuqu/bq-demo:1.2
    ports:
      # 暴露端口
      - "9983:9983"
    volumes:
      # 创建容器数据卷
      - ~/docker/bq-clusters/logs/02:/opt/apps/bq-clusters/logs/
  bq-demo-03:
    #配置容器名
    container_name: biuqu-demo-03
    # 指定镜像名
    image: biuqu/bq-demo:1.3
    ports:
      # 暴露端口
      - "9973:9973"
    volumes:
      # 创建容器数据卷
      - ~/docker/bq-clusters/logs/03:/opt/apps/bq-clusters/logs/