spring:
  profiles:
    active: root,base,nacos,circuitbreaker
  application:
    name: bq-biz
logging:
  level:
    ROOT: INFO
server:
  port: 9993
bq:
  demo:
    qr: qr-limit
  limit:
    enabled: true





